---
- hosts: openvpn-aws
  become: true

  pre_tasks:
    - name: Load configuration (with defaults from example file).
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - example.config.yml
        - config.yml

    - name: Ensure apt cache is up to date.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_facts.os_family == "Debian"

    - name: Ensure pacman cache is up to date
      community.general.pacman:
        update_cache: true
      when:
        - ansible_facts.os_family == "Archlinux"

  handlers:
    - name: Include handlers
      ansible.builtin.import_tasks: tasks/handlers.yml
      when: ansible_distribution != "Ubuntu"

  tasks:
    - name: Setup Docker.
      ansible.builtin.import_tasks: tasks/docker.yml
      when:
        - ansible_distribution != "Ubuntu"

    - name: Set up OpenVPN.
      ansible.builtin.import_tasks: tasks/openvpn.yml
      when: 
        - ovpn_enable
        - ansible_distribution != "Ubuntu"

    - name: Set up OpenVPN Monitoring.
      ansible.builtin.import_tasks: tasks/openvpn_monitoring.yml
      when: 
        - monitoring_enable
        - ansible_distribution != "Ubuntu"

    - name: Setup Docker (Ubuntu).
      ansible.builtin.include_tasks: tasks/docker_ubuntu.yml
      when:
        - ansible_distribution == "Ubuntu"

    - name: Set up OpenVPN (Ubuntu).
      ansible.builtin.include_tasks: tasks/openvpn_ubuntu.yml
      when: 
        - ovpn_enable
        - ansible_distribution == "Ubuntu"

    - name: Set up OpenVPN Monitoring (Ubuntu).
      ansible.builtin.include_tasks: tasks/openvpn_monitoring_ubuntu.yml
      when: 
        - monitoring_enable
        - ansible_distribution == "Ubuntu"